PerfumeStore.WebUI/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PerfumeStore.WebUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
    {
        // GET: Admin/Dashboard
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ClearCache()
        {
            var itemsInCache = System.Web.HttpContext.Current.Cache.GetEnumerator();

            while (itemsInCache.MoveNext())
            {
                System.Web.HttpContext.Current.Cache.Remove(itemsInCache.Key.ToString());

            }
            return View("Index");
        }
    }
}

PerfumeStore.WebUI/Areas/Admin/Controllers/StoreController.cs
using PerfumeStore.Domain.Infrastructure;
using PerfumeStore.Domain.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PerfumeStore.WebUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StoreController : Controller
    {
        // GET: Product
        public ActionResult Product()
        {
            List<Category> list = new List<Category>();
            using (PerfumeStoreDBContext context = new PerfumeStoreDBContext())
            {
                list = context.Categories.ToList();
            }

            ViewBag.Categories = list;
            List<Category> alllist = new List<Category>(list);
            alllist.Insert(0, new Category { CategoryId = 0, CategoryName = "Select All" });
            ViewBag.CategoryFilter = alllist;
            return View();
        }

        public ActionResult Category()
        {
            return View();
        }

        public ActionResult Order()
        {
            return View();
        }
    }
}

PerfumeStore.WebUI/Controllers/ProductController.cs
using PerfumeStore.Domain.Infrastructure;
using PerfumeStore.Domain.Model;
using PerfumeStore.WebUI.Areas.Admin.Models.DTO;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PerfumeStore.WebUI.Controllers
{    
    public class ProductController : Controller
    {        
        public ActionResult Male()
        {
            List<ProductDTO> list = GetProductsByCategory(1);
            ViewBag.Title = "Male";
            return View("List", list);
        }
        public ActionResult Female()
        {
            List<ProductDTO> list = GetProductsByCategory(2);
            ViewBag.Title = "Female";
            return View("List", list);
        }
        public ActionResult Unisex()
        {
            List<ProductDTO> list = GetProductsByCategory(3);
            ViewBag.Title = "Unisex";
            return View("List", list);
        }

        private List<ProductDTO> GetProductsByCategory(int categoryid)
        {
            List<ProductDTO> list = new List<ProductDTO>();
            if (System.Web.HttpContext.Current.Cache["ProductList" + categoryid] != null)
            {
                list = (List<ProductDTO>)System.Web.HttpContext.Current.Cache["ProductList" + categoryid];
            }
            else
            {
                using (PerfumeStoreDBContext context = new PerfumeStoreDBContext())
                {
                    var query = from product in context.Products
                                where product.CategoryId == categoryid
                                join category in context.Categories
                                  on product.CategoryId equals category.CategoryId
                                select new ProductDTO { ProductId = product.ProductId, ProductName = product.ProductName, CategoryId = product.CategoryId, CategoryName = category.CategoryName, Price = product.Price, Image = product.Image, Condition = product.Condition, Discount = product.Discount, UserId = product.UserId };
                    list = query.ToList();
                    System.Web.HttpContext.Current.Cache["ProductList" + categoryid] = list;
                }
            }

            return list;
        }

        public ActionResult Search(string productname)
        {
            List<ProductDTO> list = new List<ProductDTO>();

            using (PerfumeStoreDBContext context = new PerfumeStoreDBContext())
            {
                if (String.IsNullOrEmpty(productname))
                {
                    var query = from product in context.Products
                                join category in context.Categories
                                  on product.CategoryId equals category.CategoryId
                                select new ProductDTO { ProductId = product.ProductId, ProductName = product.ProductName, CategoryId = product.CategoryId, CategoryName = category.CategoryName, Price = product.Price, Image = product.Image, Condition = product.Condition, Discount = product.Discount, UserId = product.UserId };
                    list = query.ToList();
                }
                else
                {
                    var query = from product in context.Products
                                where product.ProductName.ToLower().Contains(productname.ToLower())
                                join category in context.Categories
                                  on product.CategoryId equals category.CategoryId
                                select new ProductDTO { ProductId = product.ProductId, ProductName = product.ProductName, CategoryId = product.CategoryId, CategoryName = category.CategoryName, Price = product.Price, Image = product.Image, Condition = product.Condition, Discount = product.Discount, UserId = product.UserId };
                    list = query.ToList();
                }
            }
            ViewBag.Title = "Search Result";
            return View("List", list);
        }

        public ActionResult Detail(int id)
        {
            ProductDTO model = null;
            using (PerfumeStoreDBContext context = new PerfumeStoreDBContext())
            {
                var query = from product in context.Products
                            where product.ProductId == id
                            join category in context.Categories
                              on product.CategoryId equals category.CategoryId
                            select new ProductDTO { ProductId = product.ProductId, ProductName = product.ProductName, CategoryId = product.CategoryId, CategoryName = category.CategoryName, Price = product.Price, Image = product.Image, Condition = product.Condition, Discount = product.Discount, UserId = product.UserId };
                model = query.FirstOrDefault();
            }
            return View(model);
        }

        [Authorize(Roles = "Admin, Advanced")]
        public ActionResult MyProducts()
        {
            List<Category> list = new List<Category>();
            using (PerfumeStoreDBContext context = new PerfumeStoreDBContext())
            {
                list = context.Categories.ToList();
            }

            ViewBag.Categories = list;
            List<Category> alllist = new List<Category>(list);
            alllist.Insert(0, new Category { CategoryId = 0, CategoryName = "Select All" });
            ViewBag.CategoryFilter = alllist;
            return View();
        }

        [Authorize(Roles = "Admin, Advanced")]
        public ActionResult MyProductOrders()
        {
            List<ProductOrderDTO> list = new List<ProductOrderDTO>();
            try
            {
                String userid = User.Identity.GetUserId();
                using (PerfumeStoreDBContext context = new PerfumeStoreDBContext())
                {
                    var query = from product in context.Products
                                where product.UserId == userid
                                join category in context.Categories
                                  on product.CategoryId equals category.CategoryId
                                select new ProductOrderDTO { ProductId = product.ProductId, ProductName = product.ProductName, CategoryId = product.CategoryId, CategoryName = category.CategoryName, Price = product.Price, Image = product.Image, Condition = product.Condition, Discount = product.Discount, UserId = product.UserId };
                    list = query.ToList();                    

                    foreach (ProductOrderDTO product in list)
                    {
                        var orders = from o in context.Orders
                                     join i in context.OrderItems
                                       on o.OrderId equals i.OrderId
                                     join u in context.Users
                                       on o.UserId equals u.Id
                                     where i.ProductId == product.ProductId
                                     orderby o.OrderId descending
                                     select new { o.OrderId, o.UserId, u.UserName, o.FullName, o.Address, o.City, o.State, o.Zip, o.ConfirmationNumber, o.DeliveryDate };
                        product.Orders = orders.Select(o => new OrderDTO { OrderId = o.OrderId, UserId = o.UserId, UserName = o.UserName, FullName = o.FullName, Address = o.Address, City = o.City, State = o.State, Zip = o.Zip, ConfirmationNumber = o.ConfirmationNumber, DeliveryDate = o.DeliveryDate }).ToList();

                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = "Error Occurs:" + ex.Message;
            }

            return View(list);
        }
    }
}

PerfumeStore.WebUI/Areas/Admin/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Admin: Dashboard";
}

<h2>Perfume Store Management</h2>
<div class="row">
    <div class="col-md-4">
        <ul class="list-group">
            <li class="list-group-item"><b>Statistics</b></li>
            <li class="list-group-item"><span class="badge" id="user">0</span>@Html.ActionLink("Users", "AppUser", "Account", new { area = "Admin" }, new { @class = "btn btn-primary" })</li>
            <li class="list-group-item"><span class="badge" id="role">0</span>@Html.ActionLink("Roles", "AppRole", "Account", new { area = "Admin" }, new { @class = "btn btn-primary" })</li>
            <li class="list-group-item"><span class="badge" id="product">0</span>@Html.ActionLink("Products", "Product", "Store", new { area = "Admin" }, new { @class = "btn btn-primary" })</li>
            <li class="list-group-item"><span class="badge" id="category">0</span>@Html.ActionLink("Categories", "Category", "Store", new { area = "Admin" }, new { @class = "btn btn-primary" })</li>
            <li class="list-group-item"><span class="badge" id="order">0</span>@Html.ActionLink("Orders", "Order", "Store", new { area = "Admin" }, new { @class = "btn btn-primary" })</li>
        </ul>
    </div>
    <div class="col-md-4">
        <ul class="list-group">
            <li class="list-group-item"><b>System</b></li>
            <li class="list-group-item"><span class="badge" id="user"></span>@Html.ActionLink("Clear Cache", "ClearCache", "Dashboard", new { area = "Admin" }, new { @class = "btn btn-primary"})</li>
        </ul>        
    </div>
    <div class="col-md-4"></div>
</div>
@section Scripts
{
    <script>
        $().ready(function () {
            getUserCount();
            getRoleCount();
            getProductCount();
            getCategoryCount();
            getOrderCount();
        });

        function getUserCount() {
            $.ajax({
                url: '/api/User/GetCount/',
                type: 'GET',
                success: function (result) {
                    $('#user').text(result);
                },
                error: function (result) {
                    //alert("Error:" + result);
                }
            });
        }

        function getRoleCount() {
            $.ajax({
                url: '/api/Role/GetCount/',
                type: 'GET',
                success: function (result) {
                    $('#role').text(result);
                },
                error: function (result) {
                    //alert("Error:" + result);
                }
            });
        }

        function getProductCount() {
            $.ajax({
                url: '/api/Product/GetCount/',
                type: 'GET',
                success: function (result) {
                    $('#product').text(result);
                },
                error: function (result) {
                    //alert("Error:" + result);
                }
            });
        }

        function getCategoryCount() {
            $.ajax({
                url: '/api/Category/GetCount/',
                type: 'GET',
                success: function (result) {
                    $('#category').text(result);
                },
                error: function (result) {
                    //alert("Error:" + result);
                }
            });
        }

        function getOrderCount() {
            $.ajax({
                url: '/api/Order/GetCount/',
                type: 'GET',
                success: function (result) {
                    $('#order').text(result);
                },
                error: function (result) {
                    //alert("Error:" + result);
                }
            });
        }
    </script>
}