PerfumeStore.WebUI/Controllers/MyOrderController.cs
using PerfumeStore.Domain.Infrastructure;
using PerfumeStore.WebUI.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PerfumeStore.WebUI.Controllers
{
    [Authorize]
    public class MyOrderController : Controller
    {
        // GET: MyOrder
        public ActionResult Index()
        {
            List<OrderViewModel> list = new List<OrderViewModel>();
            try
            {
                String userid = User.Identity.GetUserId();
                using (PerfumeStoreDBContext context = new PerfumeStoreDBContext())
                {
                    var orders = from o in context.Orders
                                 join u in context.Users
                                   on o.UserId equals u.Id
                                 where o.UserId == userid
                                 orderby o.OrderId descending
                                 select new { o.OrderId, o.UserId, u.UserName, o.FullName, o.Address, o.City, o.State, o.Zip, o.ConfirmationNumber, o.DeliveryDate };
                    list = orders.Select(o => new OrderViewModel { OrderId = o.OrderId, UserId = o.UserId, UserName = o.UserName, FullName = o.FullName, Address = o.Address, City = o.City, State = o.State, Zip = o.Zip, ConfirmationNumber = o.ConfirmationNumber, DeliveryDate = o.DeliveryDate }).ToList();

                    foreach (OrderViewModel order in list)
                    {
                        var orderitems = from i in context.OrderItems
                                         join p in context.Products
                                           on i.ProductId equals p.ProductId
                                         join c in context.Categories
                                           on p.CategoryId equals c.CategoryId
                                         where i.OrderId == order.OrderId
                                         select new { i.OrderItemId, i.OrderId, i.ProductId, p.ProductName, p.CategoryId, c.CategoryName, p.Price, p.Image, p.Condition, p.Discount, i.Quantity };
                        order.Items = orderitems.Select(o => new OrderItemViewModel { OrderItemId = o.OrderItemId, OrderId = o.OrderId, ProductId = o.ProductId, ProductName = o.ProductName, CategoryId = o.CategoryId, CategoryName = o.CategoryName, Price = o.Price, Image = o.Image, Condition = o.Condition, Discount = o.Discount, Quantity = o.Quantity }).ToList();
                    }
                    Session["OrderCount"] = orders.Count();
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = "Error Occurs:" + ex.Message;
            }

            return View(list);
        }

        public ActionResult Detail()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CancelOrder(int id)
        {
            using (PerfumeStoreDBContext context = new PerfumeStoreDBContext())
            {
                var order = context.Orders.Find(id);
                if (order == null)
                {
                    ViewBag.Message = string.Format("No such order [{0}] found.", id);
                }
                else {
                    context.Orders.Remove(order);
                    context.SaveChanges();
                    ViewBag.Message = string.Format("Order [{0}] has been deleted!", id);
                }
            }

            return RedirectToAction("Index");
        }
    }
}

PerfumeStore.WebUI/Views/MyOrder/Detail.cshtml
@using (Html.BeginForm("PlaceOrder", "ShoppingCart", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    <div class="form-group">
        @Html.LabelFor(o => o.UserId, new { @class = "col-md-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(o => o.UserId, new { @class = "form-control", @placeholder = "Customer Name", disabled = "true" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(o => o.Address, new { @class = "col-md-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(o => o.Address, new { @class = "form-control", @placeholder = "Customer Name", disabled = "true" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(o => o.CreditCard)
        <div class="col-sm-10">
            @Html.TextBoxFor(o => o.CreditCard, new { @class = "form-control", @placeholder = "Customer Name", disabled = "true" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            @Html.ActionLink("My Orders", "Index", "MyOrder");
        </div>
    </div>
}

PerfumeStore.WebUI/Views/MyOrder/Index.cshtml
@using PerfumeStore.Extension;
@model IEnumerable<PerfumeStore.WebUI.Models.OrderViewModel>
@{
    ViewBag.Title = "My Orders";
}
@Html.Partial("_FrontPartial")

@if (Model.Count() == 0)
{
    <h3 class="box-title">You have no order yet!</h3>
}
else
{
    foreach (var order in Model)
    {
        double total = 0;

        <div class="panel panel-info">
            <div class="panel-heading">Order Id: @order.OrderId</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-5">
                        <div class="well well-sm">
                            <div class="row">
                                <div class="col-sm-5">User Name:</div>
                                <div class="col-sm-7">@order.UserName</div>
                            </div>
                            <div class="row">
                                <div class="col-sm-5">Confirmation Number:</div>
                                <div class="col-sm-7">@order.ConfirmationNumber</div>
                            </div>
                            <div class="row">
                                <div class="col-sm-5">Delivery Date:</div>
                                <div class="col-sm-7">@order.DeliveryDate</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="well well-sm">
                            <div class="row" style="margin-bottom:20px">
                                <div class="col-sm-12"><span class="glyphicon glyphicon-plane"></span> Shipping Address</div>
                            </div>
                            <div class="row">
                                <div class="col-sm-3">Full Name:</div>
                                <div class="col-sm-9">@order.FullName:</div>
                            </div>
                            <div class="row">
                                <div class="col-sm-3">Address:</div>
                                <div class="col-sm-9">@order.Address</div>
                            </div>
                            <div class="row">
                                <div class="col-sm-3">City:</div>
                                <div class="col-sm-9">@order.City</div>
                            </div>
                            <div class="row">
                                <div class="col-sm-3">State:</div>
                                <div class="col-sm-9">@order.State</div>
                            </div>
                            <div class="row">
                                <div class="col-sm-3">Zip:</div>
                                <div class="col-sm-9">@order.Zip</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        @using (Html.BeginForm("CancelOrder", "MyOrder", FormMethod.Post, null))
                        {
                            <input type="hidden" name="id" value="@order.OrderId">
                            <input type="submit" onclick="return confirm('Are you sure to delete?')" class="btn btn-danger" value="Cancel Order" />
                        }
                    </div>
                </div>
                <hr />
                <div>                    
                    <table class="table table-striped" id="modelList">
                        <thead>
                            <tr>
                                <th>Product Id</th>
                                <th>Product Name</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Sub Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in order.Items)
                            {
                                <tr>
                                    <td>@item.ProductId</td>
                                    <td>@item.ProductName</td>
                                    <td>@Html.FormattedCurrency(item.GetDiscountedPrice())</td>
                                    <td>@item.Quantity</td>
                                    <td>@Html.FormattedCurrency(item.GetTotalCost())</td>
                                </tr>
                                total += item.GetTotalCost();
                            }
                        </tbody>
                        <tfoot>
                            <tr><td></td><td></td><td></td><td>Total:</td><td>@Html.FormattedCurrency(total)</td></tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>    
    }
}